### ISSUE TITLE
Winget API is now working again

### ISSUE THREAD

**Issue by vedantmgoyal2009** [Exorcism0666/AutoPublish#14]
- https://github.com/Exorcism0666/AutoPublish/blob/e83fc0582c14fd9b7c17666cb44003cc3c62b915/src/main.py#L51-L55
- https://github.com/Exorcism0666/AutoPublish/blob/e83fc0582c14fd9b7c17666cb44003cc3c62b915/src/pckgrbot.py#L51-L55

The API is now working again, and has moved to `https://vedantmgoyal.vercel.app/api/winget-pkgs/versions/<package id>`

**Comment by Exorcism0666** [comment]
@CoolPlayLin

**Comment by CoolPlayLin** [comment]
OK
